### ISSUE TITLE
One command build via the CLI

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/documentation#116]

**Comment by dOrgJelli** [comment]
This is documented here: https://docs.polywrap.io/guides/create-as-wrapper/build-deploy-test#build

And accomplished using the CLI's build command documented here: https://docs.polywrap.io/devtools/polywrap-cli#build-b

**Comment by dOrgJelli** [comment]
Requesting review: @namesty

**Comment by namesty** [comment]
This, in general, looks done to me. The repro-build pipeline is in a solid state right now; the optimizations that come to mind are for the Rust images. But I think that's something related to the Rust impl stories and not the build pipeline per se @dOrgJelli thoughts?

**Comment by dOrgJelli** [comment]
Yep I agree, it looks like the goals here have been accomplished "one command..."
