### ISSUE TITLE
Support for multiple wrapper implementation languages

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/documentation#117]

**Comment by dOrgJelli** [comment]
This is supported via the manifest's `language: string` field. In alpha we'll support `wasm/assemblyscript`, `wasm/rust`, and `interface`.

**Comment by dOrgJelli** [comment]
Requesting review: @namesty

**Comment by namesty** [comment]
I agree this should be marked as done. The “infrastructure” to support multiple languages is already well implemented
