### ISSUE TITLE
I want to develop wrappers in Rust

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/documentation#124]
- [x] Runtime support: https://github.com/polywrap/monorepo/pull/699 https://github.com/polywrap/monorepo/issues/217
- [x] Documentation: TODO (tracked elsewhere)
- [x] Demos: https://github.com/polywrap/demos/tree/main/hello-world/wrapper
- [x] Template Project: https://github.com/polywrap/monorepo/tree/origin/packages/templates/wasm/rust

**Comment by namesty** [comment]
Status update:

* Runtime support: in review
* Documentation: needs spec (issue creation)
* Demos: needs spec (issue creation)
* Template Project: needs spec (issue creation)

**Comment by dOrgJelli** [comment]
Status update:
* Runtime support has been merged, new release will be published soon which will unblock all other items
