### ISSUE TITLE
I can find clear, explanatory descriptions of example SDk->wrapper adaptations in our documentation.

### ISSUE THREAD

**Issue by evanjacobs** [polywrap/documentation#129]

**Comment by krisbitney** [comment]
This is possibly already complete, if the Uniswap V2 and Uniswap V3 wrappers are enough.

**Comment by evanjacobs** [comment]
@krisbitney I see that the [Uniswap v3 wrapper README is still in TODO](https://github.com/polywrap/integrations/tree/main/uniswapv3/wrapper). Is that where you think we should document the process of adapting the SDK as a wrapper? Another idea might be to document this process as a blog post.

**Comment by krisbitney** [comment]
> @krisbitney I see that the [Uniswap v3 wrapper README is still in TODO](https://github.com/polywrap/integrations/tree/main/uniswapv3/wrapper). Is that where you think we should document the process of adapting the SDK as a wrapper? Another idea might be to document this process as a blog post.

That's a great idea. I'll update the readme soon.

**Comment by krisbitney** [comment]
PR is up for readme documenting the process of adapting the SDK to a wrapper: https://github.com/polywrap/integrations/pull/37

**Comment by evanjacobs** [comment]
Yes! This is awesome. My only additional thought is that this is helpful enough that it should also live somewhere outside of the Uniswap v3 README but I don't know exactly where the right spot is. Maybe as a new "Guide" in our Docs?

**Comment by dOrgJelli** [comment]
@krisbitney, with the above PR merged, do you think this task is complete?

**Comment by krisbitney** [comment]
> @krisbitney, with the above PR merged, do you think this task is complete?

I think we can mark it complete, yeah
