### ISSUE TITLE
Our documentation provides all of the information I need to port my SDK to a production-ready wrapper.

### ISSUE THREAD

**Issue by evanjacobs** [polywrap/documentation#130]

**Comment by krisbitney** [comment]
In addition to the documentation on creating wrappers https://github.com/polywrap/documentation/issues/81, our documentation should:

- [ ] provide guidance on differences between JavaScript and AssemblyScript/Rust
- [ ] provide guidance on end-to-end wrapper testing with the Polywrap client

**Comment by dOrgJelli** [comment]
Do you think this is ready to close-out @krisbitney?

**Comment by krisbitney** [comment]
> Do you think this is ready to close-out @krisbitney?

I think we can close this out, yeah.
