### ISSUE TITLE
Our documentation provides all of the information I need to port my SDK to a production-ready plugin.

### ISSUE THREAD

**Issue by evanjacobs** [polywrap/documentation#132]

**Comment by krisbitney** [comment]
In addition to the documentation on creating wrappers https://github.com/polywrap/documentation/issues/83, our documentation should:

- [ ] explain the plugin boilerplate code and file structure
- [ ] provide guidance on usage of CLI tools that help with development
- [ ] explain how base schema types map to JavaScript types

**Comment by dOrgJelli** [comment]
Would you say this is complete @krisbitney?

**Comment by krisbitney** [comment]
> Would you say this is complete @krisbitney?

The honest answer is no. I think we need something that discusses the plugin manifest. We also need a page that discusses what's happening in this file (e.g. we should say the plugin has to extend Module and provide a PluginFactory): https://github.com/polywrap/monorepo/blob/prealpha/packages/templates/plugin/typescript/src/index.ts.

**Comment by krisbitney** [comment]
I created a PR with docs to cover this: https://github.com/polywrap/documentation/pull/188
