### ISSUE TITLE
I can find a clear and understandable description of the pros and cons of porting my SDK to a wrapper vs. to a plugin.

### ISSUE THREAD

**Issue by evanjacobs** [polywrap/documentation#134]

**Comment by krisbitney** [comment]
As Jordan and Niraj mention in https://github.com/polywrap/documentation/issues/64, porting to a plugin can take less time if the plugin is in the same language as the original SDK. Features like interfaces can facilitate gradual migration from a plugin to a wrapper.

**Comment by krisbitney** [comment]
This part of the documentation should draw on the reasons Polywrap exists in the first place.

Despite the benefits of wrappers, plugins are necessary due to the limitations of WASM: WASM does not support HTTP queries, filesystem access, or browser interaction. Wrappers will typically depend on one or more plugins, and sometimes a custom plugin may be useful to support a wrapper.

**Comment by krisbitney** [comment]
The end product can be a written description, a table of pros and cons, or any format that helps users decide whether to develop a wrapper, a plugin, or both.

**Comment by evanjacobs** [comment]
Draft of the description of the strengths of wrappers, plugins, and hybrid solution can be found here:
https://hackmd.io/gYoNKjVvSuS2Vmv1SA-h3g

**Comment by evanjacobs** [comment]
Ok, I've got a version of this doc that is ready for review. It's fairly high-level but hopefully provides some insight into how to think about the various approaches and tradeoffs:
https://hackmd.io/gYoNKjVvSuS2Vmv1SA-h3g?both

@krisbitney can you please take a look and let me know if there is other info that you think should be included here? Also, I think this content could live somewhere under the "Concepts" section of the new Docs structure but I'm open to suggestions there too:
https://github.com/polywrap/documentation-staging/blob/main/2022-Q2-restructure/outline.md

**Comment by krisbitney** [comment]
It looks great. I left a comment about using the term "wrappers" as distinct from plugins. My understanding is that we are considering plugins to be a type of wrapper.
