### ISSUE TITLE
Develop URI Resolvers: Information + Step-By-Step

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/documentation#136]
In the docs we currently have this blurb:
![image](https://user-images.githubusercontent.com/5522128/159363415-6f701ebc-f1d1-4560-91a8-18729f48e399.png)

I propose we write information about what URI resolvers are, how they work, how we built the defaults (fs, ipfs, ens), and how builders can create their own.

**Comment by nerfZael** [comment]
Blocked by:
- [ ] https://github.com/polywrap/toolchain/issues/1259
- [ ] https://github.com/polywrap/toolchain/issues/1299
