### ISSUE TITLE
Add a section to show users pre-reqs (Docker, nvm, etc.)

### ISSUE THREAD

**Issue by kev-ngo** [polywrap/documentation#14]
In `create-a-web3api`, we tell users that they need docker, docker-compose, nvm, etc. but it would be helpful to add a section on what these are / how to install / etc.

**Comment by ankorGH** [comment]
hey @kev-ngo, it's someone working on this issue. If not I will like to take a stab at it.

**Comment by kev-ngo** [comment]
@ankorGH I missed this!  Yes, please take a stab at it and message me or join our Discord server if you need any help.

**Comment by ankorGH** [comment]
thanks. I will look into it
