### ISSUE TITLE
Change Analytics labels to diferentiate from docs and other pages

### ISSUE THREAD

**Issue by rihp** [polywrap/documentation#173]
https://github.com/polywrap/documentation/blob/23ede6773690a0e18e7a46c2b6aafd1a520a1b8f/src/components/FeedbackWidget/index.js#L15

label right now is just the slugs after polywrap.io, so when we save the label we include a `docs/` prefix, this alows us to see the dif

![image](https://user-images.githubusercontent.com/12145726/168115434-966b3602-12ec-49fb-bb6d-678101f656b6.png)

**Comment by krisbitney** [comment]
To clarify, are you suggesting we add a `docs/` prefix to the `eventLabel`? The feedback widget only shows up on docs pages, so adding a prefix may be redundant.
