### ISSUE TITLE
Broken link to example react Integration project

### ISSUE THREAD

**Issue by Aishat-Akinyemi** [polywrap/documentation#192]
On [Quickstart > React Integration](https://docs.polywrap.io/quick-start/create-js-app/react-integration/). The link to the example react application is broken

**Comment by krisbitney** [comment]
> On [Quickstart > React Integration](https://docs.polywrap.io/quick-start/create-js-app/react-integration/). The link to the example react application is broken

Thank you! This has been fixed.
