### ISSUE TITLE
Move away from `query` & `graphql` words

### ISSUE THREAD

**Issue by cbrzn** [polywrap/documentation#204]
We want to move away from `query` and `graphql` words in our vocabulary. Making the documentation to talk about `execute` and `schema` (or something else, just a suggestion) will be more straight forward when it comes to describe the invocation of methods

**Comment by dOrgJelli** [comment]
I think we should use `invoke`, since that's the standard term we've been using elsewhere.

**Comment by dOrgJelli** [comment]
After looking through the docs I think this is complete.
