### ISSUE TITLE
Replace local links in readmes references docs with working links to locations in github repos

### ISSUE THREAD

**Issue by krisbitney** [polywrap/documentation#242]
Our embedding scripts in the documentation repo should be able to:
- find all relative links
- replace then with hyperlinks to github @ the branch we're cloning from

e.g. Right now if a readme has a link to `./src/transform`, the link will break. A script should automatically replace it with the correct hyperlink `https://github.com/polywrap/toolchain/tree/main/packages/schema/parse/src/transform`.

**Comment by pileks** [comment]
Hey @krisbitney is this relevant for the Hackathon happening tomorrow, or is it something we can think about later? Seems like a bit of work to get it done.

**Comment by krisbitney** [comment]
> Hey @krisbitney is this relevant for the Hackathon happening tomorrow, or is it something we can think about later? Seems like a bit of work to get it done, especially now that we're separating packages all around the place.

It isn't needed for the hackathon. We're good!
