### ISSUE TITLE
Support reference documentation for previous versions of software.

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/documentation#254]
The docs.polywrap.io reference documentation should support previous versions of the software it describes. Docusaurus has support for this, here is a link to an article I had found on the topic: https://docusaurus.io/docs/docs-multi-instance

**Comment by pileks** [comment]
Closing this as we've moved away from having a Reference section in the docs. We can revisit and reopen when we decide on the best approach for our reference docs. In the end, we can use Github tags to view the READMEs of each library if versions are important.
