### ISSUE TITLE
Document New Plugin Developer Experience

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/documentation#42]
There have been some changes to the plugin developer experience, where users can simply specify new types and methods within the `schema.graphql` file, run the `w3 plugin codegen` command, and have TypeScript types generated for them. This command uses the `web3api.plugin.yaml` file to lookup the schema and output types.

To see this in action, simply checkout an example plugin that's using a version of the toolchain >= [0.0.1-prealpha.36](https://github.com/polywrap/monorepo/releases/tag/0.0.1-prealpha.36) where the feature was added.

Here is an example project: https://github.com/polywrap/integrations/tree/main/near/plugin-js

**Comment by krisbitney** [comment]
resolved by https://github.com/polywrap/documentation/pull/188
