### ISSUE TITLE
Create a "Polywrap Development - From 0 to 100" Tutorial Video

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/documentation#48]
Create one or more tutorial videos, helping new developers learn how to use Polywarp from 0 all the way to 100.

**Comment by 0xDolus** [comment]
@dOrgJelli goes well with what I mentioned wanting to tackle mind assigning to me?

**Comment by dOrgJelli** [comment]
Sure thing @0xDolus! It should also be noted that this doesn't have to be a video, and could instead be easy-to-digest written articles.

**Comment by dOrgJelli** [comment]
Closing to due this being inactive for >6 months.
