### ISSUE TITLE
Web3API Tutorial for beginners due April 27, 2021

### ISSUE THREAD

**Issue by kev-ngo** [polywrap/documentation#5]
Take a look at the Hardhat's tutorial for beginners: https://hardhat.org/tutorial/.

It's meant to be for entry-level developers who want to try using Hardhat for hackathons. 

I don't think we can make it this simple but we could possible walk the reader through creating a simple Web3API with maybe only a query function.

**Comment by dOrgJelli** [comment]
Closing to due this being inactive for >6 months.
