### ISSUE TITLE
Documentation for base types was weak

### ISSUE THREAD

**Issue by rihp** [polywrap/documentation#52]
Kevin asks new contributor to defiwrapper, after tackling the first issue: 
*Did you have any feedback for us on the experience so far, or any major problems you ran into while working on that issue?*

> Actually working with assembly-script type was a little hard, I faced about 210 compiler errors on first run😅.
> It would be easier if there was a guide for casting to common types in polywrap.
> Documentation for base types was weak, for example which types are available for developer to work with. I searched a lot to see why Float doesn't work here!
> And some guides on how to debug (console logs) would make the life much easier.
> The one major challenge was to cast types and adopt assembly-script types to graphql output types.

**Comment by krisbitney** [comment]
resolved by https://github.com/polywrap/documentation/pull/190 and https://github.com/polywrap/documentation/pull/182
