### ISSUE TITLE
Improve: Documentation on Starting a Project From Scratch

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/documentation#56]
Some feedback from @ramilexe (loosely quoting): "There is not very good documentation for starting a wrapper from scratch. Instead the documentation tells you that you should start from a template, but instead it would be good to have simple documentation that guides you through writing a simple hello world wrapper, and directs you to larger example projects to reference."

**Comment by Niraj-Kamdar** [comment]
To add onto this. The template wrapper has full smart-contract with deploy-scripts which may not be needed for most of the wrappers. So, I think template should be as simple as possible or we should have truffle like boxes of templates like we discussed.

**Comment by evanjacobs** [comment]
FYI, this was the first user story under the "Development of New Wrappers" section of the Alpha roadmap. I'll be sure to link to this issue as part of breaking down those user stories into more fine-grained requirements.

**Comment by dOrgJelli** [comment]
Closing this as I think it is well covered in the existing documentation.
