### ISSUE TITLE
I want to learn about Polywrap and see demos/videos/examples of how I can build apps/plugins/wrappers

### ISSUE THREAD

**Issue by evanjacobs** [polywrap/documentation#61]
Related: https://github.com/polywrap/documentation/issues/56 https://github.com/polywrap/documentation/issues/65

Acceptance Criteria:
- [x] polywrap/documentation#81
- [x] polywrap/documentation#82
- [x] polywrap/documentation#83
- [x] polywrap/demos#34
- [x] polywrap/demos#44
- [x] polywrap/demos#33

**Comment by dOrgJelli** [comment]
Status updates: all sub-tasks have had their status updated. About half are in review, videos are blocked by the toolchain renaming, and one documentation task needs some attention.
