### ISSUE TITLE
I want to read documentation and see examples of moving from using standard SDKs to wrappers

### ISSUE THREAD

**Issue by krisbitney** [polywrap/documentation#64]
The documentation should provide examples of SDK-wrapper ports, as well as advice for porting their own SDKs. The advice can come in the form of a guide or a page that discusses differences between a JS SDK and an AS or Rust wrapper. For example, it would be important to know about the Ethereum plugin and about our base schema types like JSON and BigInt.

Tasks:
- [x] #129
- [x] #130
- [x] #132
- [x] #134

**Comment by dOrgJelli** [comment]
Additionally, we could advise users to "wrap" the SDK as a plugin, which might be significantly faster than writing the wrapper. Then suggest a way for the developer to gradually migrate functionality to a wrapper.

**Comment by dOrgJelli** [comment]
Additionally (might be out of scope here), we might want to have a community curated "Polywrap integrations" board, where users can add + vote on different integrations they'd like to see created.

**Comment by krisbitney** [comment]
> Additionally (might be out of scope here), we might want to have a community curated "Polywrap integrations" board, where users can add + vote on different integrations they'd like to see created.

This is a great idea but I think it's out of scope for this issue. I'm creating another issue for it.

**Comment by Niraj-Kamdar** [comment]
> Additionally, we could advise users to "wrap" the SDK as a plugin, which might be significantly faster than writing the wrapper. Then suggest a way for the developer to gradually migrate functionality to a wrapper.

The interface can really be useful while porting, 
Ex: If we divide an SDK into 6 interfaces, we can gradually replace plugin implementations of these interfaces with the wrapper implementations without needing to rewrite everything at once. This also comes with the added benefits of making wrapper easily extensible.
