### ISSUE TITLE
I want to integrate wrappers into JavaScript & TypeScript, and run in Node.JS & the browser

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/documentation#66]
- [ ] #61 
- [ ] #65

**Comment by evanjacobs** [comment]
Identify sub-tasks/issues that need to be completed in order to call this user story done.

**Comment by dOrgJelli** [comment]
Status update: since this story is functionally working today, but requires additional stories to be completed before we can call this story complete, I'm going to move this to "blocked"
