### ISSUE TITLE
README for each developer tooling due May 7 to May 15, 2021

### ISSUE THREAD

**Issue by kev-ngo** [polywrap/documentation#7]
We would improve this page: https://docs.web3api.dev/resources/developer-tooling

By making each developer tool be more detailed like Hardhat's plugin pages: https://hardhat.org/plugins/nomiclabs-hardhat-ethers.html

**Comment by kev-ngo** [comment]
Progress update:

- [x] web3api/cli, client-js, react

**Comment by dOrgJelli** [comment]
Closing to due this being inactive for >6 months.
