### ISSUE TITLE
I want to build a wrapper using the CLI

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/documentation#70]
Acceptance Criteria:
- [x] #116
- [x] #117
- [x] #118

**Comment by dOrgJelli** [comment]
Status update: all sub-tasks have been moved to "in review". Moving this story to "in review" as well.

**Comment by dOrgJelli** [comment]
Requesting review: @namesty @evanjacobs

**Comment by namesty** [comment]
Done imho @dOrgJelli
