### ISSUE TITLE
I want to deploy my wrapper using the CLI

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/documentation#74]

**Comment by dOrgJelli** [comment]
This has been implemented in the following PR: https://github.com/polywrap/monorepo/issues/670

What is needed to call this story "complete"? IMO updated documentation is one of those things. @namesty thoughts?

**Comment by namesty** [comment]
@dOrgJelli Updated docs are the only needed thing; the rest are improvements and add-ons

**Comment by dOrgJelli** [comment]
Docs & demos have been updated!
