### ISSUE TITLE
I want to deploy my wrapper using the Hub

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/documentation#75]
- [ ] Deploy from a build folder
  - [x] https://github.com/polywrap/hub/issues/224
- [ ] Deploy from an IPFS hash
  - [x] https://github.com/polywrap/hub/issues/225
- [ ] Deploy from an ENS domain
  - [x] https://github.com/polywrap/hub/issues/226
- [ ] Documentation on how to deploy using The Hub
  - [x] https://github.com/polywrap/documentation/issues/128

**Comment by dOrgJelli** [comment]
Requesting Review: @evanjacobs @namesty

**Comment by evanjacobs** [comment]
Per our conversation today, removing this from the Alpha milestone.

**Comment by dOrgJelli** [comment]
Closing this as the hub's development has been paused.
