### ISSUE TITLE
Add awesome-polywrap Link

### ISSUE THREAD

**Issue by krisbitney** [polywrap/documentation#77]
Create a community curated "Polywrap integrations" board, where users can add + vote on different integrations they'd like to see created.

**Comment by Niraj-Kamdar** [comment]
Look into [dapplist](https://thedapplist.com/), they have really nice protocol for curating the dapp, similar approach can be used for this.

**Comment by dOrgJelli** [comment]
Moving this outside of Origin-QA as it deserves its own planning.

**Comment by dOrgJelli** [comment]
This can be completely simply by adding an easy to find "awesome-polywrap" link somewhere in the site. https://awesome.polywrap.io
