### ISSUE TITLE
Follow step-by-step instructions in the documentation

### ISSUE THREAD

**Issue by codentell** [polywrap/documentation#79]
Depends on: https://github.com/polywrap/documentation/issues/43

**Comment by dOrgJelli** [comment]
Documentation exists for all project types:
wrapper - https://docs.polywrap.io/guides/create-as-wrapper/project-setup
interface - TODO
app - https://docs.polywrap.io/guides/create-js-dapp/install-client
plugin - https://docs.polywrap.io/guides/create-js-plugin

**Comment by dOrgJelli** [comment]
Closing this task as we're tracking the interface documentation elsewhere.
