### ISSUE TITLE
Documentation: wrapper development

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/documentation#81]
Needed For Completion:
- Improved documentation on:
  - [x] manifests
  - [x] schema imports
  - [x] base schema types
  - [ ] AssemblyScript and Rust support
  - [x] WASM limitations
  - [x] default plugins

**Comment by dOrgJelli** [comment]
Documentation for this exists here: https://docs.polywrap.io/guides/create-as-wrapper/project-setup

**Comment by dOrgJelli** [comment]
Requesting review: @evanjacobs @krisbitney @namesty

**Comment by krisbitney** [comment]
I think it's good as a quick-start guide. 

I'm not sure if it's in scope for this issue, but somewhere in the docs we should provide detailed information about manifests, schema imports, base schema types, AssemblyScript and Rust support, WASM limitations and default plugins, etc.

**Comment by krisbitney** [comment]
> > ...somewhere in the docs we should provide detailed information about manifests, schema imports, base schema types, AssemblyScript and Rust support, WASM limitations and default plugins, etc.
> 
> I agree @krisbitney, these are all very necessary to have in the docs IMO. I've added them to the description above. Also I think it aligns well with a new docs structure I've proposed: https://hackmd.io/@zbs1CidlRU6NAc7CvPR28w/ByAPloMm5/edit
> 
> Going to move this issue back into "ready for dev" status

I like the new structure a lot

**Comment by kev-ngo** [comment]
@dOrgJelli I'm taking on these 3 right now and had some questions:

 **1) AssemblyScript and Rust support**
 - What do you want to go over in this section?
 - E.g. did you want to talk about the clients only, wrapper implementation languages, or both?
 
**2) WASM limitations**
- Which limitations did you want to cover specifically?

**3) default plugins**
- Is this the full list of [default plugins](https://github.com/polywrap/monorepo/tree/prealpha/packages/js/plugins)?
