### ISSUE TITLE
Documentation: plugin development

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/documentation#83]
Required For Completion:
 * More detailed guide that explains:
   * [ ] all the options provided in the manifest
   * [ ] how to subinvoke
   * [ ] use interface
   * [ ] env

**Comment by dOrgJelli** [comment]
Documentation currently lives here: https://docs.polywrap.io/guides/create-js-plugin

**Comment by dOrgJelli** [comment]
Requesting review: @evanjacobs @Niraj-Kamdar

**Comment by Niraj-Kamdar** [comment]
LGTM as a Quickstart guide but we need a more detailed guide that explains all the options provided in the manifest and also explains how to subinvoke, use interface, env, etc inside the plugin.  

We also need to update this once we get new plugin dev exp PR merged

**Comment by dOrgJelli** [comment]
Docs LGTM
